Build desktop version from mobile version
dicodiaz/portfolio-first-draft pull request #4
Opened 2021-08-18 23:46 UTC by dicodiaz

I built the desktop version of the [template 2](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=48%3A27) using RWD and taking into account the following requirements:

- Use media queries in your CSS file to make your desktop version look like the template you selected.
- In order to layout the elements on the page you should use Grid and Flexbox.
- You don't need to implement any functionality that requires JavaScript.
- You must replicate the design as much as possible (e.g., font, colors, images, tests, margins) using the info from the Figma templates.
- **IMPORTANT NOTE** some Figma design templates include two input fields (for first name and last name) in the desktop version and one input field (for full name) in the mobile version (look for those cases in Contact me or Get in touch sections). **Please ignore this part of the design template and use only one input for the full name for all versions.**
  - *This applies to my template*

2021-08-19 13:03 UTC, Emmyn5600 requested changes
## STATUS: CHANGES REQUESTED :recycle:

Hi, @dicodiaz 

Great work on implementing the project requirements, however there are some issues to be solved before you get approved but you are almost there:muscle:. 
   
Changes required :writing_hand:  

       * #### Please check the comment under the review
       
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-08-19 13:03 UTC, Emmyn5600 commented on README.md
> +
- [ ] Kindly update the live link demo, it still showing us the mobile section instead of desktop section

2021-08-19 13:03 UTC, Emmyn5600 commented on img/bg_about-me_desktop.svg
> +</svg>
- [ ] Kindly, display the images for each project with the information regarding on each project.

This is for Mobile section

![port24](https://user-images.githubusercontent.com/55635977/130072018-a5eca5e9-0cd5-415b-8555-c289bb80b1ad.png)

This is for Desktop section
![port26](https://user-images.githubusercontent.com/55635977/130072475-1f44f410-ecd2-4d0f-b615-e39056a1c41a.png)

2021-08-19 13:11 UTC, dicodiaz commented on README.md
> +
Hello Emmy, thanks for the review! Are you sure this is a stopper? I have to merge my pull request before it shows and I have to be approved before merging.

2021-08-19 13:14 UTC, dicodiaz commented on img/bg_about-me_desktop.svg
> +</svg>
Hello again. May I ask for more details about this requirement? I don't really understand. Are the images not showing for you?

2021-08-19 13:17 UTC, Emmyn5600 commented on img/bg_about-me_desktop.svg
> +</svg>
It is not displaying the image project as well as the information regarding on each project, kindly check on image above for more details.

2021-08-19 13:21 UTC, Emmyn5600 commented on README.md
> +
This should an optional suggestion because deployment of the project is not mandatory on this section however you need to work on the below suggestion.

2021-08-19 13:33 UTC, dicodiaz commented on README.md
> +
Optional, got it.

2021-08-19 13:41 UTC, dicodiaz commented on img/bg_about-me_desktop.svg
> +</svg>
The thing is that it **is** showing the images for me, for both desktop and mobile versions. What could be the problem?

![image](https://user-images.githubusercontent.com/70329406/130078678-ee763d93-830b-45dd-b5d3-f13d53a6a2af.png)

![image](https://user-images.githubusercontent.com/70329406/130078909-597a2133-07cf-4f13-806c-fbf5061b3320.png)

2021-08-19 14:03 UTC, Emmyn5600 commented on img/bg_about-me_desktop.svg
> +</svg>
Sometimes it should work in your local computer. Try to update your live link demo to check if it is the problem of GitHub.

2021-08-19 14:49 UTC, dicodiaz commented on img/bg_about-me_desktop.svg
> +</svg>
I just updated my [link demo](https://dicodiaz.github.io/Portfolio/) to my build-desktop-version branch and the images work. How do you recommend that I proceed?

2021-08-19 17:52 UTC, SpaYco approved these changes
Hello 👋,

This is an additional review as a result of the second opinion request.

The images load on my end, I think this issue is caused by the network, since it took some time before it loads on my end

As this was the only reason that your project was not approved it will be approved as soon as possible.
Please ask for another review in your Dashboard and the next Code Reviewer will mark it as approve right away :)

Keep rocking 🚀!

2021-08-19 21:27 UTC, Emmyn5600 approved these changes
Hi, 
Good job so far! 👏🏼 @dicodiaz 

May I highlight the following:

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed, however use a descriptive feature branch:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
- Your project looks awesome:heavy_check_mark:

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
Great work on implementing the changes requested by the previous TSEs
 
 ## Optional suggestions
 
  - N/A
  
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-08-19 22:25 UTC, merged

2021-08-20 14:27 UTC, ramiaquista commented on css/styles-desktop.css
> +}
I think it would be a great idea if you can make each project view have a button / a tag, with the link to the project to get more information and possibly the repository.

2021-08-23 18:10 UTC, barackm reviewed
Hi @dicodiaz, 👋 

# STATUS: Approved  🎉 
Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._